### ISSUE TITLE
support for browserl.ist

### ISSUE THREAD

**Issue by FND** [faucet-pipeline/faucet-pipeline-sass#29]
[browserl.ist](http://browserl.ist) is useful for having a single place to configure things like Autoprefixer, [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) etc.

I (currently?) prefer to use a `.browserslistrc` file rather than abusing `package.json`, so IMO the following should suffice for starters:

```javascript
    prefixes: "./.browserlistrc"
```

🤔 Presumably Autoprefixer already takes care of detecting such files, so perhaps this would be enough:

```javascript
    prefixes: true
```

**Comment by moonglum** [comment]
Done. Will be released with the next release.
