### ISSUE TITLE
Support NODE_PATH when resolving imports

### ISSUE THREAD

**Issue by mrreynolds** [faucet-pipeline/faucet-pipeline-sass#30]
The standard way node supports non-default `node_modules` installation paths is by checking `NODE_PATH` when resolving dependencies.

`faucet-pipeline-sass` should support this, maybe via https://www.npmjs.com/package/node-resolve?

**Comment by FND** [comment]
This seems to be where things go awry: https://github.com/faucet-pipeline/faucet-pipeline-sass/blob/58b7d69549de2d756bbfcdd5fc0a45f719ab17d5/lib/build-config.js#L24

**Comment by moonglum** [comment]
Rsolved by bd3de27 – thanks for reporting 🙇
