### ISSUE TITLE
`from` Option

### ISSUE THREAD

**Issue by moonglum** [faucet-pipeline/faucet-pipeline-sass#37]
`npm install` gives the warning:

> Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning

**Comment by FND** [comment]
FWIW, I'd traced this to
https://github.com/postcss/postcss/blob/1416fbca02094063b28922c25accf81758d8aa4f/lib/lazy-result.es6#L191
https://github.com/postcss/postcss/blob/1416fbca02094063b28922c25accf81758d8aa4f/lib/result.es6

Not entirely sure what this means though, the changelog isn't particularly helpful:
https://github.com/postcss/postcss/blob/master/CHANGELOG.md#6015

**Comment by moonglum** [comment]
This has been solved in 1.0.0-beta.0
