### ISSUE TITLE
continued support for importing vanilla CSS files

### ISSUE THREAD

**Issue by FND** [faucet-pipeline/faucet-pipeline-sass#49]
Importing `.css` files has been deprecated: https://github.com/sass/libsass/pull/2613 (rationale in https://github.com/sass/libsass/issues/2611)

We want to continue to support this (e.g. to bundle non-Sass libraries), so we should either create a custom importer or specify `.css` as an [additional extension](https://github.com/sass/libsass/pull/2615) (preferably the former to bypass Sass processing).

**Comment by xzyfer** [comment]
Not using additional extensions does not bypass sass processing. All extensions are parsed as Sass files.

**Comment by FND** [comment]
Thanks for chiming in here, @xzyfer! Unfortunately, we're not quite sure yet what this actually means in practice: https://github.com/sass/libsass/issues/2611 states that code importing vanilla CSS files "will not be portable" - but isn't CSS a subset of Sass anyway, so what might actually go wrong as a consequence of treating `*.css` as Sass modules?

We wouldn't want for [faucet](http://faucet-pipeline.org) to depart from or even work against Sass norms, but we're uncertain what the right way is to proceed here.

**Comment by moonglum** [comment]
This is done with Release 1.0.0-rc.9 by switching from `node-sass` to `sass`.
