### ISSUE TITLE
Compiling sass fails to resolve tilde imports

### ISSUE THREAD

**Issue by bbende** [faucet-pipeline/faucet-pipeline-sass#67]
This may be more of a question than an issue, but I am not sure how to handle the following scenario..

I have my application.scss which imports bootstrap material:

`@import "bootstrap-material-design/scss/bootstrap-material-design";
`

When running a build this produces the following:
```
[ERROR] ✗ target/classes/static/stylesheets/application.css: Can't find stylesheet to import.
[ERROR] @import "~bootstrap/scss/functions"; // from bootstrap node_module
[ERROR]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR]   node_modules/bootstrap-material-design/scss/_variables.scss 56:9                @import
[ERROR]   node_modules/bootstrap-material-design/scss/_core.scss 2:9                      @import
[ERROR]   node_modules/bootstrap-material-design/scss/bootstrap-material-design.scss 3:9  @import
[ERROR]   src/main/webapp/stylesheets/application.scss 10:9                               root stylesheet
[ERROR] aborting: Error: Can't find stylesheet to import.
[ERROR] @import "~bootstrap/scss/functions"; // from bootstrap node_module
[ERROR]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR]   node_modules/bootstrap-material-design/scss/_variables.scss 56:9                @import
[ERROR]   node_modules/bootstrap-material-design/scss/_core.scss 2:9                      @import
[ERROR]   node_modules/bootstrap-material-design/scss/bootstrap-material-design.scss 3:9  @import
[ERROR]   src/main/webapp/stylesheets/application.scss 10:9                               root stylesheet
```
I had a similar problem when using Gulp and was able to use 'node-sass-tilde-importer' and tell it about includePaths: [ './node_modules' ] so that it somehow knows to how to resolve those imports.

Is there a way to achieve something similar here?

**Comment by moonglum** [comment]
Thanks again for your report 👍 

We've looked into this, and it seems to us that the `~` prefix is a proprietary extension/workaround, not a generic convention. As such, it runs contrary to faucet's basic principles, as we want source code to remain independent of (and thus portable between) build systems. Additionally, we haven't run across this in any projects yet, so we think that it's also not a de-facto standard. We therefore decided not to implement this.

In faucet-pipeline-sass, the `node_modules` folder is added in [`includePaths`](https://github.com/sass/node-sass#includepaths), so when you write `import 'boostrap/foo'` it will import `_foo.scss` from the bootstrap module. I think I will propose this solution to the bootstrap-material team. What do you think?

**Comment by bbende** [comment]
Thanks for looking into it. I'm not exactly sure why they needed to use that convention, it appears it has come up in their issues before: 

https://github.com/FezVrasta/bootstrap-material-design/issues?utf8=%E2%9C%93&q=is%3Aissue+%7Ebootstrap%2Fscss%2Ffunctions

https://github.com/FezVrasta/bootstrap-material-design/issues/1258

If the ~ prefix is not a common convention then I understand you stance of not supporting it, so feel free to close this issue.

**Comment by FND** [comment]
Thanks Bryan, we very much appreciate that.

I'd also come across those issues, but couldn't quite make sense of it all in terms of rationale. Hopefully @moonglum's suggestion to use a more portable convention will be well received.

PS: How did you come across faucet? Just curious because we haven't really made an effort promoting it beyond our own little circle so far.

**Comment by bbende** [comment]
Somehow I came across a conversation on twitter where someone linked to it and I saved it on my list of things to look at later :) 

I really like the integration with spring-boot, well documented and very easy to setup. Makes it simple for someone like me who isn't that familiar with all the front-end build tools.

**Comment by FND** [comment]
Ah, interesting, so we have to thank @michael-simons for his work on integrating faucet with Spring Boot. 🙂 Glad it's proving useful.

**Comment by michael-simons** [comment]
Thanks for letting me know, @fnd!

**Comment by moonglum** [comment]
Sorry for taking so long, but I created a ticket https://github.com/FezVrasta/bootstrap-material-design/issues/1349 and will therefore close this now. Thanks for your report 🙇
